// supported lang for text translation
const Map<String, String> supportedLanguageMap = {
  'af': 'Afrikaans',
  'ar': 'Arabic',
  'be': 'Belarusian',
  'bg': 'Bulgarian',
  'bn': 'Bengali',
  'ca': 'Catalan',
  'cs': 'Czech',
  'cy': 'Welsh',
  'da': 'Danish',
  'de': 'German',
  'el': 'Greek',
  'en': 'English',
  'eo': 'Esperanto',
  'es': 'Spanish',
  'et': 'Estonian',
  'fa': 'Persian',
  'fi': 'Finnish',
  'fr': 'French',
  'ga': 'Irish',
  'gl': 'Galician',
  'gu': 'Gujarati',
  'he': 'Hebrew',
  'hi': 'Hindi',
  'hr': 'Croatian',
  'ht': 'Haitian',
  'hu': 'Hungarian',
  'id': 'Indonesian',
  'is': 'Icelandic',
  'it': 'Italian',
  'ja': 'Japanese',
  'ka': 'Georgian',
  'kn': 'Kannada',
  'ko': 'Korean',
  'lt': 'Lithuanian',
  'lv': 'Latvian',
  'mk': 'Macedonian',
  'mr': 'Marathi',
  'ms': 'Malay',
  'mt': 'Maltese',
  'nl': 'Dutch',
  'no': 'Norwegian',
  'pl': 'Polish',
  'pt': 'Portuguese',
  'ro': 'Romanian',
  'ru': 'Russian',
  'sk': 'Slovak',
  'sl': 'Slovenian',
  'sq': 'Albanian',
  'sv': 'Swedish',
  'sw': 'Swahili',
  'ta': 'Tamil',
  'te': 'Telugu',
  'th': 'Thai',
  'tl': 'Tagalog',
  'tr': 'Turkish',
  'uk': 'Ukrainian',
  'ur': 'Urdu',
  'vi': 'Vietnamese',
  'zh': 'Chinese',
};
const Map<String, String> digitalInkLanguages = {
'af': 'Afrikaans',
'am': 'Amharic',
'ar': 'Arabic',
'as': 'Assamese',
'az-Latn-AZ': 'Azerbaijani, Latin script, regional variant for Azerbaijan',
'be': 'Belarusian',
'bg': 'Bulgarian',
'bn': 'Bangla, Bangla script',
'bn-Latn': 'Bangla, Latin script',
'ca': 'Catalan',
'cs': 'Czech',
'cy': 'Welsh',
'da': 'Danish',
'de': 'German',
'de-DE': 'German, Latin script, regional variant for Germany',
'el': 'Greek',
'en': 'English',
'en-US': 'English, Latin script, regional variant for US',
'es': 'Spanish',
'es-MX': 'Spanish, Latin script, regional variant for Mexico',
'et': 'Estonian',
'fa': 'Persian',
'fi': 'Finnish',
'fil-Latn': 'Filipino, Latin script',
'fr': 'French',
'fr-FR': 'French, Latin script, regional variant for France',
'gu': 'Gujarati',
'he': 'Hebrew',
'hi': 'Hindi',
'hr': 'Croatian',
'hu': 'Hungarian',
'id': 'Indonesian',
'is': 'Icelandic',
'it': 'Italian',
'ja': 'Japanese',
'jv-Latn': 'Javanese, Latin script',
'ka': 'Georgian',
'kk': 'Kazakh',
'km': 'Khmer',
'kn': 'Kannada',
'ko': 'Korean',
'lo': 'Lao',
'lt': 'Lithuanian',
'lv': 'Latvian',
'ml': 'Malayalam',
'mn-Cyrl': 'Mongolian, Cyrillic script',
'mr': 'Marathi',
'ms': 'Malay',
'my': 'Burmese',
'ne': 'Nepali',
'nl': 'Dutch',
'no': 'Norwegian',
'or': 'Odia',
'pa': 'Punjabi',
'pl': 'Polish',
'pt': 'Portuguese',
'pt-BR': 'Portuguese, Latin script, regional variant for Brazil',
'ro': 'Romanian, Latin script, regional variant for Romania',
'ru': 'Russian',
'sa-Deva-IN': 'Sanskrit, Devanagari script, regional variant for India',
'si': 'Sinhala',
'sk': 'Slovak',
'sl': 'Slovenian',
'sq': 'Albanian',
'sr-Cyrl': 'Serbian, Cyrillic script',
'sv': 'Swedish',
'sw': 'Swahili',
'ta': 'Tamil',
'te': 'Telugu',
'th': 'Thai',
'tr': 'Turkish',
'uk': 'Ukrainian',
'ur': 'Urdu',
'vi': 'Vietnamese',
'zh': 'Chinese',
'zh-Hans': 'Chinese, Simplified script',
'zh-Hant': 'Chinese, Traditional script',
};
// supported lang for speech to text
const Map<String, String> supportedSpeechLanguageMap = {
  '': 'Detect Language',
  'af-ZA': 'Afrikaans (South Africa)',
  'sq-AL': 'Albanian (Albania)',
  'am-ET': 'Amharic (Ethiopia)',
  'ar-DZ': 'Arabic (Algeria)',
  'ar-BH': 'Arabic (Bahrain)',
  'ar-EG': 'Arabic (Egypt)',
  'ar-IQ': 'Arabic (Iraq)',
  'ar-IL': 'Arabic (Israel)',
  'ar-JO': 'Arabic (Jordan)',
  'ar-KW': 'Arabic (Kuwait)',
  'ar-LB': 'Arabic (Lebanon)',
  'ar-MR': 'Arabic (Mauritania)',
  'ar-MA': 'Arabic (Morocco)',
  'ar-OM': 'Arabic (Oman)',
  'ar-QA': 'Arabic (Qatar)',
  'ar-SA': 'Arabic (Saudi Arabia)',
  'ar-PS': 'Arabic (State of Palestine)',
  'ar-SY': 'Arabic (Syria)',
  'ar-TN': 'Arabic (Tunisia)',
  'ar-AE': 'Arabic (United Arab Emirates)',
  'ar-YE': 'Arabic (Yemen)',
  'hy-AM': 'Armenian (Armenia)',
  'az-AZ': 'Azerbaijani (Azerbaijan)',
  'eu-ES': 'Basque (Spain)',
  'bn-BD': 'Bengali (Bangladesh)',
  'bn-IN': 'Bengali (India)',
  'bs-BA': 'Bosnian (Bosnia and Herzegovina)',
  'bg-BG': 'Bulgarian (Bulgaria)',
  'my-MM': 'Burmese (Myanmar)',
  'ca-ES': 'Catalan (Spain)',
  'cmn-Hans-CN': 'Chinese (Simplified, China)',
  'cmn-Hans-HK': 'Chinese (Simplified, Hong Kong)',
  'cmn-Hant-TW': 'Chinese (Traditional, Taiwan)',
  'yue-Hant-HK': 'Chinese, Cantonese (Traditional Hong Kong)',
  'hr-HR': 'Croatian (Croatia)',
  'cs-CZ': 'Czech (Czech Republic)',
  'da-DK': 'Danish (Denmark)',
  'nl-BE': 'Dutch (Belgium)',
  'nl-NL': 'Dutch (Netherlands)',
  'en-AU': 'English (Australia)',
  'en-CA': 'English (Canada)',
  'en-GH': 'English (Ghana)',
  'en-HK': 'English (Hong Kong)',
  'en-IN': 'English (India)',
  'en-IE': 'English (Ireland)',
  'en-KE': 'English (Kenya)',
  'en-NZ': 'English (New Zealand)',
  'en-NG': 'English (Nigeria)',
  'en-PK': 'English (Pakistan)',
  'en-PH': 'English (Philippines)',
  'en-SG': 'English (Singapore)',
  'en-ZA': 'English (South Africa)',
  'en-TZ': 'English (Tanzania)',
  'en-GB': 'English (United Kingdom)',
  'en-US': 'English (United States)',
  'et-EE': 'Estonian (Estonia)',
  'fil-PH': 'Filipino (Philippines)',
  'fi-FI': 'Finnish (Finland)',
  'fr-BE': 'French (Belgium)',
  'fr-CA': 'French (Canada)',
  'fr-FR': 'French (France)',
  'fr-CH': 'French (Switzerland)',
  'gl-ES': 'Galician (Spain)',
  'ka-GE': 'Georgian (Georgia)',
  'de-AT': 'German (Austria)',
  'de-DE': 'German (Germany)',
  'de-CH': 'German (Switzerland)',
  'el-GR': 'Greek (Greece)',
  'gu-IN': 'Gujarati (India)',
  'iw-IL': 'Hebrew (Israel)',
  'hi-IN': 'Hindi (India)',
  'hu-HU': 'Hungarian (Hungary)',
  'is-IS': 'Icelandic (Iceland)',
  'id-ID': 'Indonesian (Indonesia)',
  'it-IT': 'Italian (Italy)',
  'it-CH': 'Italian (Switzerland)',
  'ja-JP': 'Japanese (Japan)',
  'jv-ID': 'Javanese (Indonesia)',
  'kn-IN': 'Kannada (India)',
  'kk-KZ': 'Kazakh (Kazakhstan)',
  'km-KH': 'Khmer (Cambodia)',
  'rw-RW': 'Kinyarwanda (Rwanda)',
  'ko-KR': 'Korean (South Korea)',
  'lo-LA': 'Lao (Laos)',
  'lv-LV': 'Latvian (Latvia)',
  'lt-LT': 'Lithuanian (Lithuania)',
  'mk-MK': 'Macedonian (North Macedonia)',
  'ms-MY': 'Malay (Malaysia)',
  'ml-IN': 'Malayalam (India)',
  'mr-IN': 'Marathi (India)',
  'mn-MN': 'Mongolian (Mongolia)',
  'ne-NP': 'Nepali (Nepal)',
  'no-NO': 'Norwegian Bokmål (Norway)',
  'fa-IR': 'Persian (Iran)',
  'pl-PL': 'Polish (Poland)',
  'pt-BR': 'Portuguese (Brazil)',
  'pt-PT': 'Portuguese (Portugal)',
  'pa-Guru-IN': 'Punjabi (Gurmukhi India)',
  'ro-RO': 'Romanian (Romania)',
  'ru-RU': 'Russian (Russia)',
  'sr-RS': 'Serbian (Serbia)',
  'si-LK': 'Sinhala (Sri Lanka)',
  'sk-SK': 'Slovak (Slovakia)',
  'sl-SI': 'Slovenian (Slovenia)',
  'st-ZA': 'Southern Sotho (South Africa)',
  'es-AR': 'Spanish (Argentina)',
  'es-BO': 'Spanish (Bolivia)',
  'es-CL': 'Spanish (Chile)',
  'es-CO': 'Spanish (Colombia)',
  'es-CR': 'Spanish (Costa Rica)',
  'es-DO': 'Spanish (Dominican Republic)',
  'es-EC': 'Spanish (Ecuador)',
  'es-SV': 'Spanish (El Salvador)',
  'es-GT': 'Spanish (Guatemala)',
  'es-HN': 'Spanish (Honduras)',
  'es-MX': 'Spanish (Mexico)',
  'es-NI': 'Spanish (Nicaragua)',
  'es-PA': 'Spanish (Panama)',
  'es-PY': 'Spanish (Paraguay)',
  'es-PE': 'Spanish (Peru)',
  'es-PR': 'Spanish (Puerto Rico)',
  'es-ES': 'Spanish (Spain)',
  'es-US': 'Spanish (United States)',
  'es-UY': 'Spanish (Uruguay)',
  'es-VE': 'Spanish (Venezuela)',
  'su-ID': 'Sundanese (Indonesia)',
  'sw-KE': 'Swahili (Kenya)',
  'sw-TZ': 'Swahili (Tanzania)',
  'ss-Latn-ZA': 'Swati (Latin, South Africa)',
  'sv-SE': 'Swedish (Sweden)',
  'ta-IN': 'Tamil (India)',
  // Note: The input list was truncated, so this map contains only the languages up to 'Tamil (India)'.
};
